apiVersion: v1
kind: Service
metadata:
  name: advisor-svc
  namespace: packapp01
spec:
  type: ClusterIP
  ports:
  - name: http
    port: 82
    targetPort: 8080
    protocol: TCP
  selector:
    app: advisor
